apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prosper-tutor-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - tutor.prospertutor.example.com
    secretName: prosper-tutor-tls
  rules:
  - host: tutor.prospertutor.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: prosper-tutor-lite-frontend
            port:
              number: 8501