apiVersion: v1
kind: Service
metadata:
  name: prosper-tutor-lite-backend
  labels:
    app: prosper-tutor-lite
    tier: backend
spec:
  selector:
    app: prosper-tutor-lite
    tier: backend
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: prosper-tutor-lite-frontend
  labels:
    app: prosper-tutor-lite
    tier: frontend
spec:
  selector:
    app: prosper-tutor-lite
    tier: frontend
  ports:
  - protocol: TCP
    port: 8501
    targetPort: 8501
  type: LoadBalancer